name: WishesCI

on:
  push:
    branches: 
    - "develop"
    - "feature/*"
    - "bugfix/*"
    - "hotfix/*"
    - "release/*"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Verify if gradlew exists
      run: ls -la
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Gradle check
      run: ./gradlew check

    - name: Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: app/build/reports/tests/testReleaseUnitTest/

  assembleRelease:
    runs-on: ubuntu-latest

    needs: check
    
    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Gradle assembleRelease
      run: ./gradlew assembleRelease
